set -g default-terminal "tmux-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r m resize-pane -Z

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.0

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

set-option -g repeat-time 0

# History limit
set-option -g history-limit 10000\

# catppuccin setup
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse]󱀙  "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] #(memory_pressure | awk '/percentage/{print $5}') "
run '~/.config/tmux/plugins/tmux-cpu/cpu.tmux'
run '~/.config/tmux/plugins/tmux-battery/battery.tmux'
